feston_aperitif_list_aperitif:
    pattern: /v1/aperitif.{_format}
    defaults: { _controller: FestonAperitifBundle:Aperitif:list }
    requirements:
        _method:  GET

feston_aperitif_create_aperitif:
    pattern: /v1/aperitif.{_format}
    defaults: { _controller: FestonAperitifBundle:Aperitif:create }
    requirements:
        _method:  POST

feston_aperitif_update_aperitif:
    pattern: /v1/aperitif/{publicId}.{_format}
    defaults: { _controller: FestonAperitifBundle:Aperitif:update }
    requirements:
        _method:  POST
